import { PortfolioProfile } from './types';

export const INITIAL_USER = {
  id: 'usr_default_101',
  name: 'Alex Rivera',
  email: 'alex.rivera@stanford.edu',
  username: 'alexrivera',
  createdAt: '2024-09-01T10:00:00Z',
};

export const INITIAL_PROFILE: PortfolioProfile = {
  userId: 'usr_default_101',
  username: 'alexrivera',
  personal: {
    fullName: 'Alex Rivera',
    headline: 'Full-Stack Developer & UI/UX Specialist',
    bio: 'Computer Science senior at Stanford passionate about building modern, high-performance web applications, intuitive digital experiences, and scalable cloud systems.',
    targetRole: 'Software Engineer / Web & App Developer',
    location: 'Palo Alto, CA',
    email: 'alex.rivera@stanford.edu',
    phone: '+1 (650) 555-0192',
    githubUrl: 'https://github.com/alexrivera-dev',
    linkedinUrl: 'https://linkedin.com/in/alex-rivera-cs',
    portfolioUrl: 'https://portfolio-generator-pg76.vercel.app/u/alexrivera',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600',
    resumeUrl: '/resume',
    resumeFileName: 'Alex_Rivera_Resume.pdf',
    yearsExperience: '3+',
    completedProjects: '24+',
    happyClients: '50+',
    awardsWon: '6',
  },
  isPublished: true,
  education: [
    {
      id: 'edu_1',
      institution: 'Stanford University',
      degree: 'Bachelor of Science (B.S.)',
      fieldOfStudy: 'Computer Science (Systems & AI)',
      startYear: '2021',
      endYear: '2025 (Expected)',
      gpa: '3.88 / 4.00',
      coursework: 'Data Structures & Algorithms, Distributed Systems, Web Engineering, Machine Learning, UI/UX Design',
    },
  ],
  experience: [
    {
      id: 'exp_1',
      role: 'Software Engineering Intern',
      company: 'Vercel / Next.js Infrastructure Team',
      location: 'San Francisco, CA',
      startDate: 'Jun 2024',
      endDate: 'Aug 2024',
      description: [
        'Developed micro-frontend optimization tools cutting bundle sizes by 18% for 45,000+ deployments.',
        'Engineered dynamic caching mechanisms using Redis and Edge Middleware, reducing API latency by 120ms.',
        'Collaborated with senior engineers on telemetry dashboards using React, TypeScript, and Tailwind CSS.',
      ],
    },
    {
      id: 'exp_2',
      role: 'Full-Stack Lead Developer',
      company: 'Stanford Tech Lab',
      location: 'Stanford, CA',
      startDate: 'Sep 2023',
      endDate: 'May 2024',
      description: [
        'Architected a campus scheduling web app serving 12,000+ undergraduate students using Next.js and MongoDB.',
        'Implemented OAuth 2.0 authentication, role-based access control, and automated email webhooks.',
      ],
    },
  ],
  projects: [
    {
      id: 'proj_1',
      title: 'DevPulse - AI Code Reviewer',
      description: 'An AI-powered GitHub bot analyzing pull requests for security vulnerabilities, memory leaks, and performance bottlenecks using LLMs.',
      technologies: ['React', 'Next.js', 'TypeScript', 'Node.js', 'Tailwind CSS'],
      githubUrl: 'https://github.com/alexrivera-dev/devpulse-bot',
      liveUrl: 'https://devpulse-review.vercel.app',
      featured: true,
      category: 'Web Development',
      image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800',
    },
    {
      id: 'proj_2',
      title: 'CloudScale - Distributed Task Queue',
      description: 'High-throughput async task processing queue built in Go and Redis capable of handling 10,000+ concurrent jobs per second.',
      technologies: ['Go', 'Redis', 'Docker', 'Prometheus'],
      githubUrl: 'https://github.com/alexrivera-dev/cloudscale-queue',
      liveUrl: 'https://cloudscale-demo.io',
      featured: true,
      category: 'Systems Infrastructure',
      image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800',
    },
    {
      id: 'proj_3',
      title: 'Smart Task Management Tool',
      description: 'Organize your work and boost productivity with AI categorization, team Kanban boards, and automated progress reports.',
      technologies: ['TypeScript', 'React', 'Tailwind CSS', 'Framer Motion'],
      githubUrl: 'https://github.com/alexrivera-dev/smart-task-manager',
      liveUrl: 'https://smarttask-demo.vercel.app',
      featured: true,
      category: 'UI/UX Design',
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
    },
  ],
  skills: {
    languages: ['JavaScript', 'TypeScript', 'Python', 'C++', 'Go', 'SQL', 'HTML/CSS'],
    frameworks: ['React', 'Next.js', 'Node.js', 'Express.js', 'Tailwind CSS', 'FastAPI'],
    tools: ['Git / GitHub', 'Docker', 'MongoDB', 'PostgreSQL', 'Vercel', 'AWS', 'Figma'],
    softSkills: ['Agile Collaboration', 'Technical Writing', 'Problem Solving', 'Public Speaking', 'UI/UX Design'],
  },
  settings: {
    templateId: 'modern-glass',
    primaryColor: '#10b981',
    fontFamily: 'Inter',
    darkMode: false,
  },
  analytics: {
    viewsCount: 0,
    resumeDownloads: 0,
    lastViewedAt: 'No views yet',
  },
};
